name: Deploy React App to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install project dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5️⃣ Build React app (ignore ESLint warnings)
      - name: Build React app
        run: CI=false npm run build

      # 6️⃣ Deploy to Firebase Hosting
      - - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx firebase deploy --only hosting

